version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
    - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
    - ".env"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
