"""Initial

Revision ID: f048438ca6c1
Revises: 0685b4d76360
Create Date: 2023-03-10 21:38:07.888949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f048438ca6c1"
down_revision = "0685b4d76360"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_id"), "people", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_people_id"), table_name="people")
    op.drop_table("people")
    # ### end Alembic commands ###
