"""User

Revision ID: f65009d4d673
Revises: b1567cea5459
Create Date: 2023-03-13 16:29:22.345604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f65009d4d673"
down_revision = "b1567cea5459"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
